site_name: OnlineJudge_Web
site_description: Online Judge is a training tool
site_author: 8cbx
repo_url: https://github.com/8cbx/OnlineJudge_Web

pages:
- Introduction: index.md
- Deploy: deploy.md
- Init: init.md
- Start!: start.md
- Design:
  - Index: design/index.md
- API:
  - Index: api/index.md

theme: readthedocs